const pokemonList = [
    { name: "Bulbasaur", types: ["Grass", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/bulbasaur.png", pokedexEntry: "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon." },
    { name: "Ivysaur", types: ["Grass", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/ivysaur.png", pokedexEntry: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs." },
    { name: "Venusaur", types: ["Grass", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/venusaur.png", pokedexEntry: "The flower blooms when it is absorbing solar energy. It stays on the move to seek sunlight." },
    { name: "Charmander", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/charmander.png", pokedexEntry: "The flame on its tail indicates Charmander's life force. If it is healthy, the flame will be vibrant." },
    { name: "Charmeleon", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/charmeleon.png", pokedexEntry: "When it swings its burning tail, it elevates the temperature to unbearably high levels." },
    { name: "Charizard", types: ["Fire", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/charizard.png", pokedexEntry: "Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything." },
    { name: "Squirtle", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/squirtle.png", pokedexEntry: "Squirtle's shell is not merely for protection. The shell is a part of its body." },
    { name: "Wartortle", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/wartortle.png", pokedexEntry: "Wartortle is known to be very protective of its territory. It is known to be a good swimmer." },
    { name: "Blastoise", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/blastoise.png", pokedexEntry: "The jets of water it spouts from the rocket cannons on its shell can punch through thick steel." },
    { name: "Caterpie", types: ["Bug"], image: "https://img.pokemondb.net/sprites/home/normal/caterpie.png", pokedexEntry: "For protection, it releases a horrible stench from the antennae on its head." },
    { name: "Metapod", types: ["Bug"], image: "https://img.pokemondb.net/sprites/home/normal/metapod.png", pokedexEntry: "The shell is hard, but it is also fragile. It can be easily broken." },
    { name: "Butterfree", types: ["Bug", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/butterfree.png", pokedexEntry: "In battle, it flaps its wings at high speed to release highly toxic dust into the air." },
    { name: "Weedle", types: ["Bug", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/weedle.png", pokedexEntry: "It is covered with a fine hair that can cause irritation. It also has a sharp stinger on its head." },
    { name: "Kakuna", types: ["Bug", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/kakuna.png", pokedexEntry: "It is in a state of suspended animation. It can be found hanging from branches." },
    { name: "Beedrill", types: ["Bug", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/beedrill.png", pokedexEntry: "Beedrill is known for its aggressive nature. It will attack anything that enters its territory." },
    { name: "Pidgey", types: ["Normal", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/pidgey.png", pokedexEntry: "Pidgey is a common sight in forests and woods. It is known for its gentle nature." },
    { name: "Pidgeotto", types: ["Normal", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/pidgeotto.png", pokedexEntry: "Pidgeotto is known to be very territorial. It will fiercely defend its territory." },
    { name: "Pidgeot", types: ["Normal", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/pidgeot.png", pokedexEntry: "Pidgeot is known for its speed and agility. It can fly at speeds of over 200 mph." },
    { name: "Rattata", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/rattata.png", pokedexEntry: "Rattata's sharp front teeth are very effective for gnawing. It is known to be very quick." },
    { name: "Raticate", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/raticate.png", pokedexEntry: "Raticate's whiskers are very sensitive. It can detect changes in the air." },
    { name: "Spearow", types: ["Normal", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/spearow.png", pokedexEntry: "Spearow is a tiny bird Pokémon. It is known for its loud cry." },
    { name: "Fearow", types: ["Normal", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/fearow.png", pokedexEntry: "Fearow is known for its aggressive nature. It can fly at high speeds." },        { name: "Ekans", types: ["Poison"], image: "https://img.pokemondb.net/sprites/home/normal/ekans.png", pokedexEntry: "Ekans curls itself up in a spiral when it sleeps." },
    { name: "Arbok", types: ["Poison"], image: "https://img.pokemondb.net/sprites/home/normal/arbok.png", pokedexEntry: "Arbok's intimidating pattern on its hood is meant to scare off enemies." },
    { name: "Pikachu", types: ["Electric"], image: "https://img.pokemondb.net/sprites/home/normal/pikachu.png", pokedexEntry: "Pikachu can generate electricity. It stores electricity in its cheeks." },
    { name: "Raichu", types: ["Electric"], image: "https://img.pokemondb.net/sprites/home/normal/raichu.png", pokedexEntry: "Raichu's tail serves as a ground for its electric attacks." },
    { name: "Sandshrew", types: ["Ground"], image: "https://img.pokemondb.net/sprites/home/normal/sandshrew.png", pokedexEntry: "Sandshrew burrows underground to escape the heat." },
    { name: "Sandslash", types: ["Ground"], image: "https://img.pokemondb.net/sprites/home/normal/sandslash.png", pokedexEntry: "Sandslash's claws can dig through hard ground." },
    { name: "Nidoran♀", types: ["Poison"], image: "https://img.pokemondb.net/sprites/home/normal/nidoran-f.png", pokedexEntry: "Nidoran♀ has a gentle nature but can be very aggressive when threatened." },
    { name: "Nidorina", types: ["Poison"], image: "https://img.pokemondb.net/sprites/home/normal/nidorina.png", pokedexEntry: "Nidorina is known to be protective of its young." },
    { name: "Nidoqueen", types: ["Poison", "Ground"], image: "https://img.pokemondb.net/sprites/home/normal/nidoqueen.png", pokedexEntry: "Nidoqueen uses its powerful legs to run fast." },
    { name: "Nidoran♂", types: ["Poison"], image: "https://img.pokemondb.net/sprites/home/normal/nidoran-m.png", pokedexEntry: "Nidoran♂ is known for its strong sense of smell." },
    { name: "Nidorino", types: ["Poison"], image: "https://img.pokemondb.net/sprites/home/normal/nidorino.png", pokedexEntry: "Nidorino's horn is sharp and can be used for offense." },
    { name: "Nidoking", types: ["Poison", "Ground"], image: "https://img.pokemondb.net/sprites/home/normal/nidoking.png", pokedexEntry: "Nidoking is known for its strength and ferocity." },
    { name: "Clefairy", types: ["Fairy"], image: "https://img.pokemondb.net/sprites/home/normal/clefairy.png", pokedexEntry: "Clefairy is said to be a Pokémon that comes from the moon." },
    { name: "Clefable", types: ["Fairy"], image: "https://img.pokemondb.net/sprites/home/normal/clefable.png", pokedexEntry: "Clefable is known for its ability to make wishes come true." },
    { name: "Vulpix", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/vulpix.png", pokedexEntry: "Vulpix has six orange-red tails that can be used to create fire." },
    { name: "Ninetales", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/ninetales.png", pokedexEntry: "Ninetales is said to have magical powers and can live for over a thousand years." },
    { name: "Jigglypuff", types: ["Normal", "Fairy"], image: "https://img.pokemondb.net/sprites/home/normal/jigglypuff.png", pokedexEntry: "Jigglypuff uses its voice to lull opponents to sleep." },
    { name: "Wigglytuff", types: ["Normal", "Fairy"], image: "https://img.pokemondb.net/sprites/home/normal/wigglytuff.png", pokedexEntry: "Wigglytuff's body is soft and elastic, allowing it to absorb attacks." },
    { name: "Zubat", types: ["Poison", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/zubat.png", pokedexEntry: "Zubat is known for its ability to navigate in the dark using echolocation." },
    { name: "Golbat", types: ["Poison", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/golbat.png", pokedexEntry: "Golbat is known for its blood-sucking abilities." },
    { name: "Oddish", types: ["Grass", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/oddish.png", pokedexEntry: "Oddish is known to be a nocturnal Pokémon that loves to soak up moonlight." },
    { name: "Gloom", types: ["Grass", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/gloom.png", pokedexEntry: "Gloom releases a foul fragrance from the pistil of its flower." },
    { name: "Vileplume", types: ["Grass", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/vileplume.png", pokedexEntry: "Vileplume's large petals can be used to attract prey." },
    { name: "Paras", types: ["Bug", "Grass"], image: "https://img.pokemondb.net/sprites/home/normal/paras.png", pokedexEntry: "Paras is known for the mushrooms that grow on its back." },
    { name: "Parasect", types: ["Bug", "Grass"], image: "https://img.pokemondb.net/sprites/home/normal/parasect.png", pokedexEntry: "Parasect is controlled by the mushrooms on its back." },
    { name: "Venonat", types: ["Bug", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/venonat.png", pokedexEntry: "Venonat's large eyes can detect even the slightest movement." },
    { name: "Venomoth", types: ["Bug", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/venomoth.png", pokedexEntry: "Venomoth's wings are covered in poisonous scales." },
    { name: "Diglett", types: ["Ground"], image: "https://img.pokemondb.net/sprites/home/normal/diglett.png", pokedexEntry: "Diglett burrows underground to avoid detection." },
    { name: "Dugtrio", types: ["Ground"], image: "https://img.pokemondb.net/sprites/home/normal/dugtrio.png", pokedexEntry: "Dugtrio is known for its speed and ability to dig tunnels." },
    { name: "Meowth", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/meowth.png", pokedexEntry: "Meowth is known for its ability to walk on two legs." },
    { name: "Persian", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/persian.png", pokedexEntry: "Persian is known for its elegance and speed." },
    { name: "Psyduck", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/psyduck.png", pokedexEntry: "Psyduck suffers from frequent headaches." },
    { name: "Golduck", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/golduck.png", pokedexEntry: "Golduck is known for its swimming ability and speed." },
    { name: "Poliwag", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/poliwag.png", pokedexEntry: "Poliwag's skin is so thin that you can see the spiral intestines inside." },
    { name: "Poliwhirl", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/poliwhirl.png", pokedexEntry: "Poliwhirl's skin is very slippery." },
    { name: "Poliwrath", types: ["Water", "Fighting"], image: "https://img.pokemondb.net/sprites/home/normal/poliwrath.png", pokedexEntry: "Poliwrath is known for its powerful punches." },
    { name: "Abra", types: ["Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/abra.png", pokedexEntry: "Abra is known for its ability to teleport." },
    { name: "Kadabra", types: ["Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/kadabra.png", pokedexEntry: "Kadabra can bend spoons with its mind." },
    { name: "Alakazam", types: ["Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/alakazam.png", pokedexEntry: "Alakazam has an IQ of 5000." },
    { name: "Machop", types: ["Fighting"], image: "https://img.pokemondb.net/sprites/home/normal/machop.png", pokedexEntry: "Machop's muscles are strong, allowing it to lift heavy objects." },
    { name: "Machoke", types: ["Fighting"], image: "https://img.pokemondb.net/sprites/home/normal/machoke.png", pokedexEntry: "Machoke's strength is enhanced by its training." },
    { name: "Machamp", types: ["Fighting"], image: "https://img.pokemondb.net/sprites/home/normal/machamp.png", pokedexEntry: "Machamp has four powerful arms that can deliver devastating punches." },
    { name: "Bellsprout", types: ["Grass", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/bellsprout.png", pokedexEntry: "Bellsprout's thin body allows it to bend and sway to avoid attacks." },
    { name: "Weepinbell", types: ["Grass", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/weepinbell.png", pokedexEntry: "Weepinbell uses its sharp leaves to cut its prey." },
    { name: "Victreebel", types: ["Grass", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/victreebel.png", pokedexEntry: "Victreebel's mouth is wide open, ready to catch prey." },
    { name: "Tentacool", types: ["Water", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/tentacool.png", pokedexEntry: "Tentacool's body is mostly water, making it very buoyant." },
    { name: "Tentacruel", types: ["Water", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/tentacruel.png", pokedexEntry: "Tentacruel's tentacles can deliver a painful sting." },
    { name: "Geodude", types: ["Rock", "Ground"], image: "https://img.pokemondb.net/sprites/home/normal/geodude.png", pokedexEntry: "Geodude can be found in rocky areas, often rolling down hills." },
    { name: "Graveler", types: ["Rock", "Ground"], image: "https://img.pokemondb.net/sprites/home/normal/graveler.png", pokedexEntry: "Graveler's body is covered in hard rocks, making it very tough." },
    { name: "Golem", types: ["Rock", "Ground"], image: "https://img.pokemondb.net/sprites/home/normal/golem.png", pokedexEntry: "Golem can explode when threatened, causing massive damage." },
    { name: "Ponyta", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/ponyta.png", pokedexEntry: "Ponyta's mane is made of flames that burn brightly." },
    { name: "Rapidash", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/rapidash.png", pokedexEntry: "Rapidash can run at incredible speeds, leaving a trail of flames." },
    { name: "Slowpoke", types: ["Water", "Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/slowpoke.png", pokedexEntry: "Slowpoke is known for its slow reactions and laid-back nature." },
    { name: "Slowbro", types: ["Water", "Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/slowbro.png", pokedexEntry: "Slowbro is often seen with a Shellder attached to its tail." },
    { name: "Magnemite", types: ["Electric", "Steel"], image: "https://img.pokemondb.net/sprites/home/normal/magnemite.png", pokedexEntry: "Magnemite is attracted to magnetic fields." },
    { name: "Magneton", types: ["Electric", "Steel"], image: "https://img.pokemondb.net/sprites/home/normal/magneton.png", pokedexEntry: "Magneton is formed by three Magnemite joining together." },
    { name: "Farfetchd", types: ["Normal", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/farfetchd.png", pokedexEntry: "Farfetch'd is known for carrying a leek, which it uses in battle." },
    { name: "Doduo", types: ["Normal", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/doduo.png", pokedexEntry: "Doduo has two heads that can act independently." },
    { name: "Dodrio", types: ["Normal", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/dodrio.png", pokedexEntry: "Dodrio can run at speeds of up to 60 mph." },
    { name: "Seel", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/seel.png", pokedexEntry: "Seel is known for its playful nature and love of swimming." },
    { name: "Dewgong", types: ["Water", "Ice"], image: "https://img.pokemondb.net/sprites/home/normal/dewgong.png", pokedexEntry: "Dewgong can swim gracefully through the water." },
    { name: "Grimer", types: ["Poison"], image: "https://img.pokemondb.net/sprites/home/normal/grimer.png", pokedexEntry: "Grimer is made of sludge and can be found in polluted areas." },
    { name: "Muk", types: ["Poison"], image: "https://img.pokemondb.net/sprites/home/normal/muk.png", pokedexEntry: "Muk's body is composed of toxic sludge." },
    { name: "Shellder", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/shellder.png", pokedexEntry: "Shellder's shell is very hard and can protect it from attacks." },
    { name: "Cloyster", types: ["Water", "Ice"], image: "https://img.pokemondb.net/sprites/home/normal/cloyster.png", pokedexEntry: "Cloyster can shoot water at high pressure." },
    { name: "Gastly", types: ["Ghost", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/gastly.png", pokedexEntry: "Gastly is made of gas and can become invisible." },
    { name: "Haunter", types: ["Ghost", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/haunter.png", pokedexEntry: "Haunter can pass through walls and is known for its mischievous nature." },
    { name: "Gengar", types: ["Ghost", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/gengar.png", pokedexEntry: "Gengar is known for its ability to hide in shadows." },
    { name: "Onix", types: ["Rock", "Ground"], image: "https://img.pokemondb.net/sprites/home/normal/onix.png", pokedexEntry: "Onix is a giant rock snake that can burrow through the ground." },
    { name: "Drowzee", types: ["Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/drowzee.png", pokedexEntry: "Drowzee is known for its ability to put others to sleep." },
    { name: "Hypno", types: ["Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/hypno.png", pokedexEntry: "Hypno uses its pendulum to hypnotize its prey." },
    { name: "Krabby", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/krabby.png", pokedexEntry: "Krabby is known for its powerful pincers." },
    { name: "Kingler", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/kingler.png", pokedexEntry: "Kingler's pincers are strong enough to crush rocks." },
    { name: "Voltorb", types: ["Electric"], image: "https://img.pokemondb.net/sprites/home/normal/voltorb.png", pokedexEntry: "Voltorb is known for its resemblance to a Poké Ball." },
    { name: "Electrode", types: ["Electric"], image: "https://img.pokemondb.net/sprites/home/normal/electrode.png", pokedexEntry: "Electrode can explode when it feels threatened." },
    { name: "Exeggcute", types: ["Grass", "Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/exeggcute.png", pokedexEntry: "Exeggcute is known for its ability to communicate with each other." },
    { name: "Exeggutor", types: ["Grass", "Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/exeggutor.png", pokedexEntry: "Exeggutor has three heads that can act independently." },
    { name: "Cubone", types: ["Ground"], image: "https://img.pokemondb.net/sprites/home/normal/cubone.png", pokedexEntry: "Cubone wears the skull of its deceased mother." },
    { name: "Marowak", types: ["Ground"], image: "https://img.pokemondb.net/sprites/home/normal/marowak.png", pokedexEntry: "Marowak is known for its vengeful spirit." },
    { name: "Hitmonlee", types: ["Fighting"], image: "https://img.pokemondb.net/sprites/home/normal/hitmonlee.png", pokedexEntry: "Hitmonlee is known for its powerful kicks." },
    { name: "Hitmonchan", types: ["Fighting"], image: "https://img.pokemondb.net/sprites/home/normal/hitmonchan.png", pokedexEntry: "Hitmonchan is known for its boxing skills." },
    { name: "Lickitung", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/lickitung.png", pokedexEntry: "Lickitung's tongue is long and can be used to catch prey." },
    { name: "Koffing", types: ["Poison"], image: "https://img.pokemondb.net/sprites/home/normal/koffing.png", pokedexEntry: "Koffing releases toxic gas from its body." },
    { name: "Weezing", types: ["Poison"], image: "https://img.pokemondb.net/sprites/home/normal/weezing.png", pokedexEntry: "Weezing has two heads that can release toxic gas." },
    { name: "Rhyhorn", types: ["Ground", "Rock"], image: "https://img.pokemondb.net/sprites/home/normal/rhyhorn.png", pokedexEntry: "Rhyhorn's body is hard as rock. It can easily knock a truck flying." },
    { name: "Rhydon", types: ["Ground", "Rock"], image: "https://img.pokemondb.net/sprites/home/normal/rhydon.png", pokedexEntry: "Rhydon is the first Pokémon to be created by humans. It can punch a hole through a steel wall." },
    { name: "Chansey", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/chansey.png", pokedexEntry: "Chansey lays highly nutritious eggs on an everyday basis." },
    { name: "Tangela", types: ["Grass"], image: "https://img.pokemondb.net/sprites/home/normal/tangela.png", pokedexEntry: "Tangela's body is covered with a thick, blue vine. It is said to be a plant." },
    { name: "Kangaskhan", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/kangaskhan.png", pokedexEntry: "Kangaskhan is a protective parent. It carries its baby in its pouch." },
    { name: "Horsea", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/horsea.png", pokedexEntry: "Horsea can easily hide itself in water. It is known to be a good swimmer." },
    { name: "Seadra", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/seadra.png", pokedexEntry: "Seadra's spines can pierce through the skin of its prey." },
    { name: "Goldeen", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/goldeen.png", pokedexEntry: "Goldeen is known for its beautiful fins. It can swim gracefully." },
    { name: "Seaking", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/seaking.png", pokedexEntry: "Seaking's horn can pierce through the toughest of materials." },
    { name: "Staryu", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/staryu.png", pokedexEntry: "Staryu can regenerate its limbs. It is often found in shallow waters." },
    { name: "Starmie", types: ["Water", "Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/starmie.png", pokedexEntry: "Starmie has a gem that can shine brightly. It is said to be a star." },
    { name: "Mr. Mime", types: ["Psychic", "Fairy"], image: "https://img.pokemondb.net/sprites/home/normal/mr-mime.png", pokedexEntry: "Mr. Mime uses its miming abilities to create invisible walls." },
    { name: "Scyther", types: ["Bug", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/scyther.png", pokedexEntry: "Scyther is known for its speed and sharp scythes." },
    { name: "Jynx", types: ["Ice", "Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/jynx.png", pokedexEntry: "Jynx uses its singing voice to mesmerize its opponents." },
    { name: "Electabuzz", types: ["Electric"], image: "https://img.pokemondb.net/sprites/home/normal/electabuzz.png", pokedexEntry: "Electabuzz generates electricity. It can be seen in power plants." },
    { name: "Magmar", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/magmar.png", pokedexEntry: "Magmar's body temperature is extremely high. It can melt anything." },
    { name: "Pinsir", types: ["Bug"], image: "https://img.pokemondb.net/sprites/home/normal/pinsir.png", pokedexEntry: "Pinsir's pincers can crush anything. It is a fierce fighter." },
    { name: "Tauros", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/tauros.png", pokedexEntry: "Tauros is known for its strength and aggression." },
    { name: "Magikarp", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/magikarp.png", pokedexEntry: "Magikarp is known for its uselessness. It can only splash." },
    { name: "Gyarados", types: ["Water", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/gyarados.png", pokedexEntry: "Gyarados is known for its ferocity. It can destroy everything." },
    { name: "Lapras", types: ["Water", "Ice"], image: "https://img.pokemondb.net/sprites/home/normal/lapras.png", pokedexEntry: "Lapras is known for its gentle nature. It can ferry people across water." },
    { name: "Ditto", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/ditto.png", pokedexEntry: "Ditto can transform into any Pokémon. It is a master of disguise." },
    { name: "Eevee", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/eevee.png", pokedexEntry: "Eevee has the ability to evolve into multiple forms." },
    { name: "Vaporeon", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/vaporeon.png", pokedexEntry: "Vaporeon can melt into water. It is known for its aquatic abilities." },
    { name: "Jolteon", types: ["Electric"], image: "https://img.pokemondb.net/sprites/home/normal/jolteon.png", pokedexEntry: "Jolteon can generate electricity. It is known for its speed." },
    { name: "Flareon", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/flareon.png", pokedexEntry: "Flareon has a flame that burns hotter than a furnace." },
    { name: "Porygon", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/porygon.png", pokedexEntry: "Porygon is a virtual Pokémon. It can convert its body into data." },
    { name: "Omanyte", types: ["Rock", "Water"], image: "https://img.pokemondb.net/sprites/home/normal/omanyte.png", pokedexEntry: "Omanyte is a fossil Pokémon. It is known for its spiral shell." },
    { name: "Omastar", types: ["Rock", "Water"], image: "https://img.pokemondb.net/sprites/home/normal/omastar.png", pokedexEntry: "Omastar's tentacles can capture prey. It is a fierce predator." },
    { name: "Kabuto", types: ["Rock", "Water"], image: "https://img.pokemondb.net/sprites/home/normal/kabuto.png", pokedexEntry: "Kabuto is a fossil Pokémon. It is known for its hard shell." },
    { name: "Kabutops", types: ["Rock", "Water"], image: "https://img.pokemondb.net/sprites/home/normal/kabutops.png", pokedexEntry: "Kabutops has sharp scythes for arms. It is a skilled hunter." },
    { name: "Aerodactyl", types: ["Rock", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/aerodactyl.png", pokedexEntry: "Aerodactyl is a prehistoric Pokémon. It is known for its speed." },
    { name: "Snorlax", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/snorlax.png", pokedexEntry: "Snorlax is known for its massive size and appetite." },
    { name: "Articuno", types: ["Ice", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/articuno.png", pokedexEntry: "Articuno is a legendary bird Pokémon. It is known for its icy powers." },
    { name: "Zapdos", types: ["Electric", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/zapdos.png", pokedexEntry: "Zapdos is a legendary bird Pokémon. It can generate powerful electricity." },
    { name: "Moltres", types: ["Fire", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/moltres.png", pokedexEntry: "Moltres is a legendary bird Pokémon. It is known for its fiery wings." },
    { name: "Dratini", types: ["Dragon"], image: "https://img.pokemondb.net/sprites/home/normal/dratini.png", pokedexEntry: "Dratini is a rare Pokémon. It is known for its graceful swimming." },
    { name: "Dragonair", types: ["Dragon"], image: "https://img.pokemondb.net/sprites/home/normal/dragonair.png", pokedexEntry: "Dragonair is known for its mystical powers. It can control the weather." },
    { name: "Dragonite", types: ["Dragon", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/dragonite.png", pokedexEntry: "Dragonite is a powerful Pokémon. It can fly at incredible speeds." },
    { name: "Mewtwo", types: ["Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/mewtwo.png", pokedexEntry: "Mewtwo is a genetically engineered Pokémon. It is known for its psychic abilities." },
    { name: "Mew", types: ["Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/mew.png", pokedexEntry: "Mew is a mythical Pokémon. It is said to have the DNA of all Pokémon." },
    //Generation 2 Pokemon
    { name: "Chikorita", types: ["Grass"], image: "https://img.pokemondb.net/sprites/home/normal/chikorita.png", pokedexEntry: "Chikorita's leaf is a vital part of its biology. It uses the leaf to sense the temperature and humidity." },
    { name: "Bayleef", types: ["Grass"], image: "https://img.pokemondb.net/sprites/home/normal/bayleef.png", pokedexEntry: "Bayleef's aroma has a soothing effect. It can calm aggressive Pokémon." },
    { name: "Meganium", types: ["Grass"], image: "https://img.pokemondb.net/sprites/home/normal/meganium.png", pokedexEntry: "Meganium's breath has the power to revive dead plants and flowers." },
    { name: "Cyndaquil", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/cyndaquil.png", pokedexEntry: "Cyndaquil's back burns brightly when it is excited." },
    { name: "Quilava", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/quilava.png", pokedexEntry: "Quilava can shoot fire from its back. It is known to be a fierce fighter." },
    { name: "Typhlosion", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/typhlosion.png", pokedexEntry: "Typhlosion can unleash a powerful flame that can melt anything." },
    { name: "Totodile", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/totodile.png", pokedexEntry: "Totodile is known for its playful nature and sharp teeth." },
    { name: "Croconaw", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/croconaw.png", pokedexEntry: "Croconaw is a strong swimmer and can hold its breath for a long time." },
    { name: "Feraligatr", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/feraligatr.png", pokedexEntry: "Feraligatr is known for its powerful jaws and aggressive nature." },
    { name: "Sentret", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/sentret.png", pokedexEntry: "Sentret stands on its tail to see over tall grass." },
    { name: "Furret", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/furret.png", pokedexEntry: "Furret is known for its speed and agility." },
    { name: "Hoothoot", types: ["Normal", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/hoothoot.png", pokedexEntry: "Hoothoot is active at night and can rotate its head 180 degrees." },
    { name: "Noctowl", types: ["Normal", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/noctowl.png", pokedexEntry: "Noctowl is known for its wisdom and keen eyesight." },
    { name: "Ledyba", types: ["Bug", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/ledyba.png", pokedexEntry: "Ledyba is known for its ability to fly gracefully." },
    { name: "Ledian", types: ["Bug", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/ledian.png", pokedexEntry: "Ledian is known for its speed and agility." },
    { name: "Spinarak", types: ["Bug", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/spinarak.png", pokedexEntry: "Spinarak spins webs to catch its prey." },
    { name: "Ariados", types: ["Bug", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/ariados.png", pokedexEntry: "Ariados can create strong webs to trap its prey." },
    { name: "Crobat", types: ["Poison", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/crobat.png", pokedexEntry: "Crobat is known for its speed and agility in the air." },
    { name: "Chinchou", types: ["Water", "Electric"], image: "https://img.pokemondb.net/sprites/home/normal/chinchou.png", pokedexEntry: "Chinchou can generate electricity to stun its prey." },
    { name: "Lanturn", types: ["Water", "Electric"], image: "https://img.pokemondb.net/sprites/home/normal/lanturn.png", pokedexEntry: "Lanturn can illuminate dark waters with its light." },
    { name: "Pichu", types: ["Electric"], image: "https://img.pokemondb.net/sprites/home/normal/pichu.png", pokedexEntry: "Pichu is known for its cuteness and small size." },
    { name: "Cleffa", types: ["Fairy"], image: "https://img.pokemondb.net/sprites/home/normal/cleffa.png", pokedexEntry: "Cleffa is known for its playful nature." },
    { name: "Igglybuff", types: ["Normal", "Fairy"], image: "https://img.pokemondb.net/sprites/home/normal/igglybuff.png", pokedexEntry: "Igglybuff can sing a lullaby that puts others to sleep." },
    { name: "Togepi", types: ["Fairy"], image: "https://img.pokemondb.net/sprites/home/normal/togepi.png", pokedexEntry: "Togepi is known for its ability to bring happiness." },
    { name: "Togetic", types: ["Fairy", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/togetic.png", pokedexEntry: "Togetic is known for its ability to spread joy." },
    { name: "Natu", types: ["Psychic", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/natu.png", pokedexEntry: "Natu can see the future and is known for its intelligence." },
    { name: "Xatu", types: ["Psychic", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/xatu.png", pokedexEntry: "Xatu can see the past and future." },
    { name: "Mareep", types: ["Electric"], image: "https://img.pokemondb.net/sprites/home/normal/mareep.png", pokedexEntry: "Mareep's wool can generate electricity." },
    { name: "Flaaffy", types: ["Electric"], image: "https://img.pokemondb.net/sprites/home/normal/flaaffy.png", pokedexEntry: "Flaaffy can store electricity in its wool." },
    { name: "Ampharos", types: ["Electric"], image: "https://img.pokemondb.net/sprites/home/normal/ampharos.png", pokedexEntry: "Ampharos can generate powerful electric shocks." },
    { name: "Bellossom", types: ["Grass"], image: "https://img.pokemondb.net/sprites/home/normal/bellossom.png", pokedexEntry: "Bellossom is known for its beautiful flowers." },
    { name: "Marill", types: ["Water", "Fairy"], image: "https://img.pokemondb.net/sprites/home/normal/marill.png", pokedexEntry: "Marill is known for its round shape and playful nature." },
    { name: "Azumarill", types: ["Water", "Fairy"], image: "https://img.pokemondb.net/sprites/home/normal/azumarill.png", pokedexEntry: "Azumarill is known for its swimming ability." },
    { name: "Sudowoodo", types: ["Rock"], image: "https://img.pokemondb.net/sprites/home/normal/sudowoodo.png", pokedexEntry: "Sudowoodo is known for its tree-like appearance." },
    { name: "Politoed", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/politoed.png", pokedexEntry: "Politoed is known for its singing ability." },
    { name: "Hoppip", types: ["Grass", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/hoppip.png", pokedexEntry: "Hoppip can float in the air using its fluffy body." },
    { name: "Skiploom", types: ["Grass", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/skiploom.png", pokedexEntry: "Skiploom can ride the wind to travel long distances." },
    { name: "Jumpluff", types: ["Grass", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/jumpluff.png", pokedexEntry: "Jumpluff can float on the wind for long periods." },
    { name: "Aipom", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/aipom.png", pokedexEntry: "Aipom is known for its long tail and playful nature." },
    { name: "Sunkern", types: ["Grass"], image: "https://img.pokemondb.net/sprites/home/normal/sunkern.png", pokedexEntry: "Sunkern is known for its small size and sunny disposition." },
    { name: "Sunflora", types: ["Grass"], image: "https://img.pokemondb.net/sprites/home/normal/sunflora.png", pokedexEntry: "Sunflora is known for its ability to soak up sunlight." },
    { name: "Yanma", types: ["Bug", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/yanma.png", pokedexEntry: "Yanma is known for its speed and agility." },
    { name: "Wooper", types: ["Water", "Ground"], image: "https://img.pokemondb.net/sprites/home/normal/wooper.png", pokedexEntry: "Wooper is known for its slimy body." },
    { name: "Quagsire", types: ["Water", "Ground"], image: "https://img.pokemondb.net/sprites/home/normal/quagsire.png", pokedexEntry: "Quagsire is known for its laid-back nature." },
    { name: "Espeon", types: ["Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/espeon.png", pokedexEntry: "Espeon is known for its psychic abilities." },
    { name: "Umbreon", types: ["Dark"], image: "https://img.pokemondb.net/sprites/home/normal/umbreon.png", pokedexEntry: "Umbreon is known for its stealth and agility." },
    { name: "Leafeon", types: ["Grass"], image: "https://img.pokemondb.net/sprites/home/normal/leafeon.png", pokedexEntry: "Leafeon is known for its ability to blend in with nature." },
    { name: "Glaceon", types: ["Ice"], image: "https://img.pokemondb.net/sprites/home/normal/glaceon.png", pokedexEntry: "Glaceon is known for its icy breath." },
    { name: "Sylveon", types: ["Fairy"], image: "https://img.pokemondb.net/sprites/home/normal/sylveon.png", pokedexEntry: "Sylveon is known for its charming appearance." },
    { name: "Murkrow", types: ["Dark", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/murkrow.png", pokedexEntry: "Murkrow is known for its mischievous nature." },
    { name: "Honchkrow", types: ["Dark", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/honchkrow.png", pokedexEntry: "Honchkrow is known for its leadership among Murkrow." },
    { name: "Shuckle", types: ["Bug", "Rock"], image: "https://img.pokemondb.net/sprites/home/normal/shuckle.png", pokedexEntry: "Shuckle is known for its ability to store berries." },
    { name: "Granbull", types: ["Fairy"], image: "https://img.pokemondb.net/sprites/home/normal/granbull.png", pokedexEntry: "Granbull is known for its strong jaws." },
    { name: "Qwilfish", types: ["Water", "Poison"], image: "https://img.pokemondb.net/sprites/home/normal/qwilfish.png", pokedexEntry: "Qwilfish is known for its ability to inflate its body." },
    { name: "Scizor", types: ["Bug", "Steel"], image: "https://img.pokemondb.net/sprites/home/normal/scizor.png", pokedexEntry: "Scizor is known for its speed and strength." },
    { name: "Sneasel", types: ["Dark", "Ice"], image: "https://img.pokemondb.net/sprites/home/normal/sneasel.png", pokedexEntry: "Sneasel is known for its sharp claws." },
    { name: "Teddiursa", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/teddiursa.png", pokedexEntry: "Teddiursa is known for its cute appearance." },
    { name: "Ursaring", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/ursaring.png", pokedexEntry: "Ursaring is known for its strength." },
    { name: "Slugma", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/slugma.png", pokedexEntry: "Slugma is known for its molten body." },
    { name: "Magcargo", types: ["Fire", "Rock"], image: "https://img.pokemondb.net/sprites/home/normal/magcargo.png", pokedexEntry: "Magcargo is known for its hot shell." },
    { name: "Swinub", types: ["Ice", "Ground"], image: "https://img.pokemondb.net/sprites/home/normal/swinub.png", pokedexEntry: "Swinub is known for its ability to find food under the snow." },
    { name: "Piloswine", types: ["Ice", "Ground"], image: "https://img.pokemondb.net/sprites/home/normal/piloswine.png", pokedexEntry: "Piloswine is known for its thick fur." },
    { name: "Corsola", types: ["Water", "Rock"], image: "https://img.pokemondb.net/sprites/home/normal/corsola.png", pokedexEntry: "Corsola is known for its coral-like appearance." },
    { name: "Remoraid", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/remoraid.png", pokedexEntry: "Remoraid is known for its ability to shoot water." },
    { name: "Octillery", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/octillery.png", pokedexEntry: "Octillery is known for its powerful water jets." },
    { name: "Delibird", types: ["Ice", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/delibird.png", pokedexEntry: "Delibird is known for delivering gifts." },
    { name: "Mantine", types: ["Water", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/mantine.png", pokedexEntry: "Mantine is known for its graceful swimming." },
    { name: "Skarmory", types: ["Steel", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/skarmory.png", pokedexEntry: "Skarmory is known for its tough metal body." },
    { name: "Houndoom", types: ["Dark", "Fire"], image: "https://img.pokemondb.net/sprites/home/normal/houndoom.png", pokedexEntry: "Houndoom is known for its fiery breath." },
    { name: "Kingdra", types: ["Water", "Dragon"], image: "https://img.pokemondb.net/sprites/home/normal/kingdra.png", pokedexEntry: "Kingdra is known for its powerful water attacks." },
    { name: "Phanpy", types: ["Ground"], image: "https://img.pokemondb.net/sprites/home/normal/phanpy.png", pokedexEntry: "Phanpy is known for its playful nature." },
    { name: "Donphan", types: ["Ground"], image: "https://img.pokemondb.net/sprites/home/normal/donphan.png", pokedexEntry: "Donphan is known for its strength and speed." },
    { name: "Porygon2", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/porygon2.png", pokedexEntry: "Porygon2 is known for its ability to adapt." },
    { name: "Stantler", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/stantler.png", pokedexEntry: "Stantler is known for its antlers." },
    { name: "Smeargle", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/smeargle.png", pokedexEntry: "Smeargle is known for its ability to paint." },
    { name: "Tyrogue", types: ["Fighting"], image: "https://img.pokemondb.net/sprites/home/normal/tyrogue.png", pokedexEntry: "Tyrogue is known for its fighting skills." },
    { name: "Hitmontop", types: ["Fighting"], image: "https://img.pokemondb.net/sprites/home/normal/hitmontop.png", pokedexEntry: "Hitmontop is known for its spinning attacks." },
    { name: "Smoochum", types: ["Ice", "Psychic"], image: "https://img.pokemondb.net/sprites/home/normal/smoochum.png", pokedexEntry: "Smoochum is known for its cute appearance." },
    { name: "Elekid", types: ["Electric"], image: "https://img.pokemondb.net/sprites/home/normal/elekid.png", pokedexEntry: "Elekid is known for its electric abilities." },
    { name: "Magby", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/magby.png", pokedexEntry: "Magby is known for its fiery personality." },
    { name: "Miltank", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/miltank.png", pokedexEntry: "Miltank is known for its milk production." },
    { name: "Blissey", types: ["Normal"], image: "https://img.pokemondb.net/sprites/home/normal/blissey.png", pokedexEntry: "Blissey is known for its healing abilities." },
    { name: "Raikou", types: ["Electric"], image: "https://img.pokemondb.net/sprites/home/normal/raikou.png", pokedexEntry: "Raikou is known for its speed and electric attacks." },
    { name: "Entei", types: ["Fire"], image: "https://img.pokemondb.net/sprites/home/normal/entei.png", pokedexEntry: "Entei is known for its powerful fire attacks." },
    { name: "Suicune", types: ["Water"], image: "https://img.pokemondb.net/sprites/home/normal/suicune.png", pokedexEntry: "Suicune is known for its graceful swimming." },
    { name: "Larvitar", types: ["Rock", "Ground"], image: "https://img.pokemondb.net/sprites/home/normal/larvitar.png", pokedexEntry: "Larvitar is known for its strong will." },
    { name: "Pupitar", types: ["Rock", "Ground"], image: "https://img.pokemondb.net/sprites/home/normal/pupitar.png", pokedexEntry: "Pupitar is known for its tough exterior." },
    { name: "Tyranitar", types: ["Rock", "Dark"], image: "https://img.pokemondb.net/sprites/home/normal/tyranitar.png", pokedexEntry: "Tyranitar is known for its immense power." },
    { name: "Lugia", types: ["Psychic", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/lugia.png", pokedexEntry: "Lugia is known as the guardian of the seas." },
    { name: "Ho-Oh", types: ["Fire", "Flying"], image: "https://img.pokemondb.net/sprites/home/normal/ho-oh.png", pokedexEntry: "Ho-Oh is known for its rainbow-colored wings." },
    { name: "Celebi", types: ["Psychic", "Grass"], image: "https://img.pokemondb.net/sprites/home/normal/celebi.png", pokedexEntry: "Celebi is known for its time-traveling abilities." }
];

document.getElementById('randomize-button').addEventListener('click', () => {
    const gen1PokemonList = pokemonList.slice(0, 151); // Get the first 151 Pokémon
    const randomIndex = Math.floor(Math.random() * gen1PokemonList.length);
    const selectedPokemon = gen1PokemonList[randomIndex];

    displayPokemon(selectedPokemon);
});

// New Gen 2 button event listener
document.getElementById('gen2-button').addEventListener('click', () => {
    const gen2PokemonList = pokemonList.slice(151); // Get Pokémon from index 151 onwards
    const randomIndex = Math.floor(Math.random() * gen2PokemonList.length);
    const selectedPokemon = gen2PokemonList[randomIndex];

    displayPokemon(selectedPokemon);
});

// Function to display Pokémon information
function displayPokemon(pokemon) {
    document.getElementById('pokemon-image').src = pokemon.image;
    document.getElementById('pokemon-name').innerText = pokemon.name;

    // Clear previous types
    const typesContainer = document.getElementById('pokemon-types');
    typesContainer.innerHTML = ''; // Clear previous types

    // Create a span for each type and apply styles
    pokemon.types.forEach(type => {
        const typeSpan = document.createElement('span');
        typeSpan.innerText = type;
        typeSpan.className = 'pokemon-type ' + type.toLowerCase(); // Add class for styling
        typesContainer.appendChild(typeSpan);
    });

    document.getElementById('pokemon-pokedexEntry').innerText = `Pokédex Entry: ${pokemon.pokedexEntry}`;
}